/**
 * Builds the puzzle packs. Run with Node 24 (type stripping): `node scripts/puzzles.ts`.
 *
 *   --levels              generate puzzles/levels.json (refuses to overwrite without --force)
 *   --only-level K        regenerate one level in place (needs --force)
 *   --daily-until DAY     append daily puzzles up to DAY (YYYY-MM-DD); existing days never change
 *
 * Every slot has its own seed (level number or epoch day), so regenerating one slot or
 * extending the dailies leaves every other puzzle untouched.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { addDays, dailySize, epochDay, LAUNCH_DAY, weekday } from '../shared/day.ts';
import { generate, type Target } from '../src/engine/generate.ts';
import { dailyTarget, LEVEL_COUNT, levelTarget } from '../src/engine/ladder.ts';
import type { PackPuzzle } from '../src/engine/puzzle.ts';
import { subSeed } from '../src/engine/rng.ts';

export const LEVEL_BASE = 0x51acd0c0;
export const DAILY_BASE = 0xd0c0da11;
export const GEN_VERSION = 1;

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUZ = join(root, 'puzzles');
const DAILY_DIR = join(PUZ, 'daily');
const LEVELS_FILE = join(PUZ, 'levels.json');
const ANSWERS_FILE = join(root, 'shared', 'dailyAnswers.ts');
const MANIFEST_FILE = join(PUZ, 'manifest.json');

export function levelSeed(k: number): number {
  return subSeed(LEVEL_BASE, k);
}

export function dailySeed(day: string): number {
  return subSeed(DAILY_BASE, epochDay(day));
}

/** Generate a slot, retrying with derived seeds when the generator fails or repeats a puzzle. */
export function makeSlot(target: Target, seed: number, ids: Set<string>): PackPuzzle {
  for (let j = 0; j < 30; j++) {
    const g = generate(target, j === 0 ? seed : subSeed(seed, 1000 + j));
    if (g && !ids.has(g.id)) {
      ids.add(g.id);
      return { n: g.n, r: g.r, s: g.s, id: g.id, d: g.d, t: g.t, w: g.w };
    }
  }
  throw new Error(`could not generate slot ${seed}: ${JSON.stringify(target)}`);
}

function line(p: PackPuzzle): string {
  return JSON.stringify(p);
}

function writeLevels(levels: PackPuzzle[]): void {
  const body = levels.map((p) => `    ${line(p)}`).join(',\n');
  writeFileSync(LEVELS_FILE, `{\n  "v": 1,\n  "levels": [\n${body}\n  ]\n}\n`);
}

interface MonthFile {
  v: 1;
  month: string;
  days: Record<string, PackPuzzle>;
}

function readDaily(): Map<string, PackPuzzle> {
  const out = new Map<string, PackPuzzle>();
  if (!existsSync(DAILY_DIR)) return out;
  for (const f of readdirSync(DAILY_DIR).sort()) {
    if (!f.endsWith('.json')) continue;
    const m = JSON.parse(readFileSync(join(DAILY_DIR, f), 'utf8')) as MonthFile;
    for (const [d, p] of Object.entries(m.days)) out.set(d, p);
  }
  return out;
}

function writeDaily(all: Map<string, PackPuzzle>): void {
  mkdirSync(DAILY_DIR, { recursive: true });
  const months = new Map<string, [string, PackPuzzle][]>();
  for (const [d, p] of [...all].sort((a, b) => a[0].localeCompare(b[0]))) {
    const m = d.slice(0, 7);
    if (!months.has(m)) months.set(m, []);
    months.get(m)!.push([d, p]);
  }
  for (const [m, days] of months) {
    const body = days.map(([d, p]) => `    "${d}": ${line(p)}`).join(',\n');
    writeFileSync(join(DAILY_DIR, `${m}.json`), `{\n  "v": 1,\n  "month": "${m}",\n  "days": {\n${body}\n  }\n}\n`);
  }
  const days = [...all.keys()].sort();
  const answers = days.map((d) => all.get(d)!.s).join(',');
  writeFileSync(
    ANSWERS_FILE,
    `// Generated by scripts/puzzles.ts from puzzles/daily; do not edit.\n` +
      `// Daily Duck solutions, one per UTC day from DAILY_FIRST, for the leaderboard Worker.\n` +
      `export const DAILY_FIRST = '${days[0]}';\n` +
      `export const DAILY_LAST = '${days[days.length - 1]}';\n` +
      `export const DAILY_ANSWERS =\n  '${answers}';\n`,
  );
}

function sha256(file: string): string {
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

function writeManifest(): void {
  const days = [...readDaily().keys()].sort();
  const months: Record<string, string> = {};
  for (const f of readdirSync(DAILY_DIR).sort()) if (f.endsWith('.json')) months[f.replace('.json', '')] = sha256(join(DAILY_DIR, f));
  const manifest = {
    generator: GEN_VERSION,
    levels: { count: LEVEL_COUNT, sha256: existsSync(LEVELS_FILE) ? sha256(LEVELS_FILE) : null },
    daily: { first: days[0] ?? null, last: days[days.length - 1] ?? null, months },
  };
  writeFileSync(MANIFEST_FILE, `${JSON.stringify(manifest, null, 2)}\n`);
}

function readLevels(): PackPuzzle[] {
  if (!existsSync(LEVELS_FILE)) return [];
  return (JSON.parse(readFileSync(LEVELS_FILE, 'utf8')) as { levels: PackPuzzle[] }).levels;
}

function main(argv: string[]): void {
  const has = (f: string) => argv.includes(f);
  const val = (f: string) => {
    const i = argv.indexOf(f);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const force = has('--force');
  mkdirSync(PUZ, { recursive: true });
  const ids = new Set<string>();
  let levels = readLevels();
  const daily = readDaily();
  for (const p of daily.values()) ids.add(p.id);

  if (has('--levels')) {
    if (levels.length && !force) throw new Error('levels.json exists; published levels must not change (use --force to overwrite)');
    levels = [];
    const t0 = Date.now();
    for (let k = 1; k <= LEVEL_COUNT; k++) {
      levels.push(makeSlot(levelTarget(k), levelSeed(k), ids));
      if (k % 20 === 0) console.log(`level ${k}/${LEVEL_COUNT} (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
    }
    writeLevels(levels);
  } else {
    for (const p of levels) ids.add(p.id);
  }

  const only = val('--only-level');
  if (only) {
    if (!force) throw new Error('--only-level rewrites a published level; add --force');
    const k = Number(only);
    const old = levels[k - 1];
    if (!old) throw new Error(`no level ${k}`);
    ids.delete(old.id);
    levels[k - 1] = makeSlot(levelTarget(k), levelSeed(k), ids);
    writeLevels(levels);
  }

  const until = val('--daily-until');
  if (until) {
    const known = [...daily.keys()].sort();
    let day = known.length ? addDays(known[known.length - 1]!, 1) : LAUNCH_DAY;
    const t0 = Date.now();
    let made = 0;
    while (epochDay(day) <= epochDay(until)) {
      daily.set(day, makeSlot(dailyTarget(weekday(day), dailySize(day)), dailySeed(day), ids));
      made++;
      if (made % 50 === 0) console.log(`daily ${day} (${made}, ${((Date.now() - t0) / 1000).toFixed(0)} s)`);
      day = addDays(day, 1);
    }
    writeDaily(daily);
  }
  writeManifest();
  console.log(`levels: ${levels.length}, daily days: ${daily.size}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main(process.argv.slice(2));
